# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosquito', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.CharField(default='ww', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.CharField(default='ww', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
