# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosquito', '0002_auto_20170311_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='report_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
