# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosquito', '0003_user_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
