# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosquito', '0004_auto_20170313_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 13, 12, 42, 28, 891125)),
        ),
    ]
